/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.time.Instant;
import java.util.Arrays;

/**
 *
 * @author jsaunders
 */
public class LoginScreen extends javax.swing.JFrame {
    

            
    
//    MainProgram runProgram = new MainProgram();
    

   
public boolean countUp(){
    
    Instant second = Instant.now();
       long x = 0;
       x = Instant.now().getEpochSecond();
       if (x < 1){
           return false;
       }
       else {
           return true;
       }
    
   
   
}
       
//   /[P, a, s, s, w, 0, r, d]


   private String parseString(char[] password){
      String pwdI = Arrays.toString(password);
       String newPSWD = "";
      int x =1;
      int y = x+3;
      
      for (int i = 1; i<pwdI.length(); i+=3) {
          char ch = pwdI.charAt(i);
         String character = Character.toString(ch);
         newPSWD +=character;
      }
      
    return newPSWD;

   }
    
    
    private boolean checkCred(String usrNameI, String pWDI){
        
        String vUN = "ticklemeelmo";
        String vPWD = "Passw0rd";
        
       if((vUN.equals(usrNameI))&&(vPWD.equals(pWDI))){
        return true;
    }
      
       else{
           return false;
       }
               
        
    }
    
    public void displayPrompt()  {
       
      //use timer method
        jLoginFail.setVisible(true);
     //   jLoginFail.setVisible(false);
        //after time close message
    }
        

    /**
     * Creates new form NewJFrame
     */
    public LoginScreen() {
        
        initComponents();
         jLogin.setVisible(true);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRoom = new javax.swing.JDialog();
        cButton = new javax.swing.JButton();
        homeRoom = new javax.swing.JLabel();
        JChat = new javax.swing.JDialog();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLogin = new javax.swing.JDialog();
        uName = new javax.swing.JTextField();
        pwd = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        sbmtB = new javax.swing.JButton();
        jLoginFail = new javax.swing.JDialog();
        jTextField2 = new javax.swing.JTextField();

        jRoom.setMaximumSize(new java.awt.Dimension(400, 700));
        jRoom.setMinimumSize(new java.awt.Dimension(390, 700));
        jRoom.setPreferredSize(new java.awt.Dimension(395, 710));

        cButton.setForeground(new java.awt.Color(187, 0, 187));
        cButton.setToolTipText("");
        cButton.setBorder(null);
        cButton.setBorderPainted(false);
        cButton.setOpaque(false);
        cButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cButtonActionPerformed(evt);
            }
        });

        homeRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/pictures/homescreenshadowsmaller.png"))); // NOI18N
        homeRoom.setMaximumSize(new java.awt.Dimension(450, 725));
        homeRoom.setMinimumSize(new java.awt.Dimension(400, 700));
        homeRoom.setPreferredSize(new java.awt.Dimension(400, 720));

        javax.swing.GroupLayout jRoomLayout = new javax.swing.GroupLayout(jRoom.getContentPane());
        jRoom.getContentPane().setLayout(jRoomLayout);
        jRoomLayout.setHorizontalGroup(
            jRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRoomLayout.createSequentialGroup()
                .addGroup(jRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jRoomLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(cButton, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(homeRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jRoomLayout.setVerticalGroup(
            jRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRoomLayout.createSequentialGroup()
                .addGroup(jRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jRoomLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(cButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(homeRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        JChat.setMinimumSize(new java.awt.Dimension(385, 700));

        jTextField1.setForeground(new java.awt.Color(163, 163, 181));
        jTextField1.setText("jTextField1");

        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(55, 55, 71));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/pictures/chatroombackgroundsmaller.png"))); // NOI18N

        javax.swing.GroupLayout JChatLayout = new javax.swing.GroupLayout(JChat.getContentPane());
        JChat.getContentPane().setLayout(JChatLayout);
        JChatLayout.setHorizontalGroup(
            JChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JChatLayout.createSequentialGroup()
                .addGroup(JChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(JChatLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(JChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(45, 45, 45))
        );
        JChatLayout.setVerticalGroup(
            JChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JChatLayout.createSequentialGroup()
                .addGroup(JChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JChatLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addGroup(JChatLayout.createSequentialGroup()
                        .addGap(600, 600, 600)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );

        jLogin.setMinimumSize(new java.awt.Dimension(400, 720));

        uName.setBackground(new java.awt.Color(163, 163, 181));
        uName.setForeground(new java.awt.Color(55, 55, 71));
        uName.setBorder(null);

        pwd.setBackground(new java.awt.Color(163, 163, 181));
        pwd.setForeground(new java.awt.Color(55, 55, 71));
        pwd.setBorder(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/pictures/loginscreenshadowsmaller.png"))); // NOI18N

        sbmtB.setOpaque(false);
        sbmtB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbmtBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLoginLayout = new javax.swing.GroupLayout(jLogin.getContentPane());
        jLogin.getContentPane().setLayout(jLoginLayout);
        jLoginLayout.setHorizontalGroup(
            jLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLoginLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(uName, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jLoginLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pwd, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jLoginLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(sbmtB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jLoginLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jLoginLayout.setVerticalGroup(
            jLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLoginLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(uName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(pwd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172)
                .addComponent(sbmtB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jLoginLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLoginFail.setMinimumSize(new java.awt.Dimension(400, 300));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(55, 55, 71));
        jTextField2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("WRONG CREDENTIALS!");
        jTextField2.setToolTipText("");
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 124, 0), 2));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLoginFailLayout = new javax.swing.GroupLayout(jLoginFail.getContentPane());
        jLoginFail.getContentPane().setLayout(jLoginFailLayout);
        jLoginFailLayout.setHorizontalGroup(
            jLoginFailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLoginFailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        jLoginFailLayout.setVerticalGroup(
            jLoginFailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLoginFailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(375, 666));
        setMinimumSize(new java.awt.Dimension(375, 666));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 666, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
        jRoom.setVisible(false);
        JChat.setVisible(true);
    }//GEN-LAST:event_cButtonActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void sbmtBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbmtBActionPerformed
 if (checkCred(uName.getText(),parseString(pwd.getPassword()))==true){
        jLogin.setVisible(false);
        jRoom.setVisible(true);
        }
        else{
            
                displayPrompt();
                
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_sbmtBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                
                new LoginScreen();
                
                
            }
            
           
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog JChat;
    private javax.swing.JButton cButton;
    private javax.swing.JLabel homeRoom;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JDialog jLogin;
    private javax.swing.JDialog jLoginFail;
    private javax.swing.JDialog jRoom;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPasswordField pwd;
    private javax.swing.JButton sbmtB;
    private javax.swing.JTextField uName;
    // End of variables declaration//GEN-END:variables

}